# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.9.2, generator: @autorest/python@6.1.9)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from copy import deepcopy
from typing import Any

from azure.core import PipelineClient
from azure.core.rest import HttpRequest, HttpResponse

from ._configuration import SwaggerPetstoreConfiguration
from ._operations import SwaggerPetstoreOperationsMixin
from ._serialization import Deserializer, Serializer


class SwaggerPetstore(SwaggerPetstoreOperationsMixin):  # pylint: disable=client-accepts-api-version-keyword
    """This is a sample server Petstore server.  You can find out more about Swagger at
    `http://swagger.io <http://swagger.io>`_ or on `irc.freenode.net, #swagger
    <http://swagger.io/irc/>`_.  For this sample, you can use the api key ``special-key`` to test
    the authorization filters.

    :keyword endpoint: Service URL. Known values are: "https://petstore.swagger.io/v2" and
     "http://petstore.swagger.io/v2". Default value is "https://petstore.swagger.io/v2".
    :paramtype endpoint: str
    """

    def __init__(  # pylint: disable=missing-client-constructor-parameter-credential
        self, *, endpoint: str = "https://petstore.swagger.io/v2", **kwargs: Any
    ) -> None:
        super().__init__()
        self._config = SwaggerPetstoreConfiguration(**kwargs)
        self._client = PipelineClient(base_url=endpoint, config=self._config, **kwargs)

        self._serialize = Serializer()
        self._deserialize = Deserializer()
        self._serialize.client_side_validation = False

    def send_request(self, request: HttpRequest, **kwargs: Any) -> HttpResponse:
        """Runs the network request through the client's chained policies.

        >>> from azure.core.rest import HttpRequest
        >>> request = HttpRequest("GET", "https://www.example.org/")
        <HttpRequest [GET], url: 'https://www.example.org/'>
        >>> response = client.send_request(request)
        <HttpResponse: 200 OK>

        For more information on this code flow, see https://aka.ms/azsdk/dpcodegen/python/send_request

        :param request: The network request you want to make. Required.
        :type request: ~azure.core.rest.HttpRequest
        :keyword bool stream: Whether the response payload will be streamed. Defaults to False.
        :return: The response of your network call. Does not do error handling on your response.
        :rtype: ~azure.core.rest.HttpResponse
        """

        request_copy = deepcopy(request)
        request_copy.url = self._client.format_url(request_copy.url)
        return self._client.send_request(request_copy, **kwargs)

    def close(self):
        # type: () -> None
        self._client.close()

    def __enter__(self):
        # type: () -> SwaggerPetstore
        self._client.__enter__()
        return self

    def __exit__(self, *exc_details):
        # type: (Any) -> None
        self._client.__exit__(*exc_details)
