//go:build go1.18
// +build go1.18

// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.9.2, generator: @autorest/go@4.0.0-preview.44)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// DO NOT EDIT.

package 

const host = "https://petstore.swagger.io/v2"

type Get0ItemsItem string

const (
	Get0ItemsItemAvailable Get0ItemsItem = "available"
	Get0ItemsItemPending Get0ItemsItem = "pending"
	Get0ItemsItemSold Get0ItemsItem = "sold"
)

// PossibleGet0ItemsItemValues returns the possible values for the Get0ItemsItem const type.
func PossibleGet0ItemsItemValues() []Get0ItemsItem {
	return []Get0ItemsItem{	
		Get0ItemsItemAvailable,
		Get0ItemsItemPending,
		Get0ItemsItemSold,
	}
}

// HostOptions - choices for server host
type HostOptions string

const (
	// HostOptionsHTTPPetstoreSwaggerIoV2 - host: http://petstore.swagger.io/v2
	HostOptionsHTTPPetstoreSwaggerIoV2 HostOptions = "http://petstore.swagger.io/v2"
	// HostOptionsHTTPSPetstoreSwaggerIoV2 - host: https://petstore.swagger.io/v2
	HostOptionsHTTPSPetstoreSwaggerIoV2 HostOptions = "https://petstore.swagger.io/v2"
)

// PossibleHostOptionsValues returns the possible values for the HostOptions const type.
func PossibleHostOptionsValues() []HostOptions {
	return []HostOptions{	
		HostOptionsHTTPPetstoreSwaggerIoV2,
		HostOptionsHTTPSPetstoreSwaggerIoV2,
	}
}

// OrderStatus - Order Status
type OrderStatus string

const (
	OrderStatusApproved OrderStatus = "approved"
	OrderStatusDelivered OrderStatus = "delivered"
	OrderStatusPlaced OrderStatus = "placed"
)

// PossibleOrderStatusValues returns the possible values for the OrderStatus const type.
func PossibleOrderStatusValues() []OrderStatus {
	return []OrderStatus{	
		OrderStatusApproved,
		OrderStatusDelivered,
		OrderStatusPlaced,
	}
}

// PetStatus - pet status in the store
type PetStatus string

const (
	PetStatusAvailable PetStatus = "available"
	PetStatusPending PetStatus = "pending"
	PetStatusSold PetStatus = "sold"
)

// PossiblePetStatusValues returns the possible values for the PetStatus const type.
func PossiblePetStatusValues() []PetStatus {
	return []PetStatus{	
		PetStatusAvailable,
		PetStatusPending,
		PetStatusSold,
	}
}

