//go:build go1.18
// +build go1.18

// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.9.2, generator: @autorest/go@4.0.0-preview.44)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// DO NOT EDIT.

package 

import (
	"io"
	"time"
)

type APIResponse struct {
	Code *int32 `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Type *string `json:"type,omitempty"`
}

type Category struct {
	ID *int64 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

type Order struct {
	Complete *bool `json:"complete,omitempty"`
	ID *int64 `json:"id,omitempty"`
	PetID *int64 `json:"petId,omitempty"`
	Quantity *int32 `json:"quantity,omitempty"`
	ShipDate *time.Time `json:"shipDate,omitempty"`

	// Order Status
	Status *OrderStatus `json:"status,omitempty"`
}

type PathsN18Gb4PetPetidPostRequestbodyContentApplicationXWwwFormUrlencodedSchema struct {
	// Updated name of the pet
	Name *string `json:"name,omitempty"`

	// Updated status of the pet
	Status *string `json:"status,omitempty"`
}

type PathsQ1AtbnPetPetidUploadimagePostRequestbodyContentMultipartFormDataSchema struct {
	// Additional data to pass to server
	AdditionalMetadata *string `json:"additionalMetadata,omitempty"`

	// file to upload
	File *io.ReadSeekCloser `json:"file,omitempty"`
}

type Pet struct {
	// REQUIRED
	Name *string `json:"name,omitempty"`

	// REQUIRED
	PhotoUrls []*string `json:"photoUrls,omitempty"`
	Category *Category `json:"category,omitempty"`
	ID *int64 `json:"id,omitempty"`

	// pet status in the store
	Status *PetStatus `json:"status,omitempty"`
	Tags []*Tag `json:"tags,omitempty"`
}

// SwaggerPetstoreClientAddPetOptions contains the optional parameters for the SwaggerPetstoreClient.AddPet method.
type SwaggerPetstoreClientAddPetOptions struct {
	// placeholder for future optional parameters
}

// SwaggerPetstoreClientCreateUserOptions contains the optional parameters for the SwaggerPetstoreClient.CreateUser method.
type SwaggerPetstoreClientCreateUserOptions struct {
	// placeholder for future optional parameters
}

// SwaggerPetstoreClientCreateUsersWithArrayInputOptions contains the optional parameters for the SwaggerPetstoreClient.CreateUsersWithArrayInput
// method.
type SwaggerPetstoreClientCreateUsersWithArrayInputOptions struct {
	// placeholder for future optional parameters
}

// SwaggerPetstoreClientCreateUsersWithListInputOptions contains the optional parameters for the SwaggerPetstoreClient.CreateUsersWithListInput
// method.
type SwaggerPetstoreClientCreateUsersWithListInputOptions struct {
	// placeholder for future optional parameters
}

// SwaggerPetstoreClientDeleteOrderOptions contains the optional parameters for the SwaggerPetstoreClient.DeleteOrder method.
type SwaggerPetstoreClientDeleteOrderOptions struct {
	// placeholder for future optional parameters
}

// SwaggerPetstoreClientDeletePetOptions contains the optional parameters for the SwaggerPetstoreClient.DeletePet method.
type SwaggerPetstoreClientDeletePetOptions struct {
	APIKey *string
}

// SwaggerPetstoreClientDeleteUserOptions contains the optional parameters for the SwaggerPetstoreClient.DeleteUser method.
type SwaggerPetstoreClientDeleteUserOptions struct {
	// placeholder for future optional parameters
}

// SwaggerPetstoreClientFindPetsByStatusOptions contains the optional parameters for the SwaggerPetstoreClient.FindPetsByStatus
// method.
type SwaggerPetstoreClientFindPetsByStatusOptions struct {
	// placeholder for future optional parameters
}

// SwaggerPetstoreClientFindPetsByTagsOptions contains the optional parameters for the SwaggerPetstoreClient.FindPetsByTags
// method.
type SwaggerPetstoreClientFindPetsByTagsOptions struct {
	// placeholder for future optional parameters
}

// SwaggerPetstoreClientGetInventoryOptions contains the optional parameters for the SwaggerPetstoreClient.GetInventory method.
type SwaggerPetstoreClientGetInventoryOptions struct {
	// placeholder for future optional parameters
}

// SwaggerPetstoreClientGetOrderByIDOptions contains the optional parameters for the SwaggerPetstoreClient.GetOrderByID method.
type SwaggerPetstoreClientGetOrderByIDOptions struct {
	// placeholder for future optional parameters
}

// SwaggerPetstoreClientGetPetByIDOptions contains the optional parameters for the SwaggerPetstoreClient.GetPetByID method.
type SwaggerPetstoreClientGetPetByIDOptions struct {
	// placeholder for future optional parameters
}

// SwaggerPetstoreClientGetUserByNameOptions contains the optional parameters for the SwaggerPetstoreClient.GetUserByName
// method.
type SwaggerPetstoreClientGetUserByNameOptions struct {
	// placeholder for future optional parameters
}

// SwaggerPetstoreClientLoginUserOptions contains the optional parameters for the SwaggerPetstoreClient.LoginUser method.
type SwaggerPetstoreClientLoginUserOptions struct {
	// placeholder for future optional parameters
}

// SwaggerPetstoreClientLogoutUserOptions contains the optional parameters for the SwaggerPetstoreClient.LogoutUser method.
type SwaggerPetstoreClientLogoutUserOptions struct {
	// placeholder for future optional parameters
}

// SwaggerPetstoreClientPlaceOrderOptions contains the optional parameters for the SwaggerPetstoreClient.PlaceOrder method.
type SwaggerPetstoreClientPlaceOrderOptions struct {
	// placeholder for future optional parameters
}

// SwaggerPetstoreClientUpdatePetOptions contains the optional parameters for the SwaggerPetstoreClient.UpdatePet method.
type SwaggerPetstoreClientUpdatePetOptions struct {
	// placeholder for future optional parameters
}

// SwaggerPetstoreClientUpdatePetWithFormOptions contains the optional parameters for the SwaggerPetstoreClient.UpdatePetWithForm
// method.
type SwaggerPetstoreClientUpdatePetWithFormOptions struct {
	// Updated name of the pet
	Name *string
	// Updated status of the pet
	Status *string
}

// SwaggerPetstoreClientUpdateUserOptions contains the optional parameters for the SwaggerPetstoreClient.UpdateUser method.
type SwaggerPetstoreClientUpdateUserOptions struct {
	// placeholder for future optional parameters
}

// SwaggerPetstoreClientUploadFileOptions contains the optional parameters for the SwaggerPetstoreClient.UploadFile method.
type SwaggerPetstoreClientUploadFileOptions struct {
	// Additional data to pass to server
	AdditionalMetadata *string
	// file to upload
	File io.ReadSeekCloser
}

type Tag struct {
	ID *int64 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

type User struct {
	Email *string `json:"email,omitempty"`
	FirstName *string `json:"firstName,omitempty"`
	ID *int64 `json:"id,omitempty"`
	LastName *string `json:"lastName,omitempty"`
	Password *string `json:"password,omitempty"`
	Phone *string `json:"phone,omitempty"`

	// User Status
	UserStatus *int32 `json:"userStatus,omitempty"`
	Username *string `json:"username,omitempty"`
}

