//go:build go1.18
// +build go1.18

// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.9.2, generator: @autorest/go@4.0.0-preview.44)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// DO NOT EDIT.

package 

import "time"

// SwaggerPetstoreClientAddPetResponse contains the response from method SwaggerPetstoreClient.AddPet.
type SwaggerPetstoreClientAddPetResponse struct {
	// placeholder for future response values
}

// SwaggerPetstoreClientCreateUserResponse contains the response from method SwaggerPetstoreClient.CreateUser.
type SwaggerPetstoreClientCreateUserResponse struct {
	// placeholder for future response values
}

// SwaggerPetstoreClientCreateUsersWithArrayInputResponse contains the response from method SwaggerPetstoreClient.CreateUsersWithArrayInput.
type SwaggerPetstoreClientCreateUsersWithArrayInputResponse struct {
	// placeholder for future response values
}

// SwaggerPetstoreClientCreateUsersWithListInputResponse contains the response from method SwaggerPetstoreClient.CreateUsersWithListInput.
type SwaggerPetstoreClientCreateUsersWithListInputResponse struct {
	// placeholder for future response values
}

// SwaggerPetstoreClientDeleteOrderResponse contains the response from method SwaggerPetstoreClient.DeleteOrder.
type SwaggerPetstoreClientDeleteOrderResponse struct {
	// placeholder for future response values
}

// SwaggerPetstoreClientDeletePetResponse contains the response from method SwaggerPetstoreClient.DeletePet.
type SwaggerPetstoreClientDeletePetResponse struct {
	// placeholder for future response values
}

// SwaggerPetstoreClientDeleteUserResponse contains the response from method SwaggerPetstoreClient.DeleteUser.
type SwaggerPetstoreClientDeleteUserResponse struct {
	// placeholder for future response values
}

// SwaggerPetstoreClientFindPetsByStatusResponse contains the response from method SwaggerPetstoreClient.FindPetsByStatus.
type SwaggerPetstoreClientFindPetsByStatusResponse struct {
	// Array of Pet
	PetArray []*Pet
}

// SwaggerPetstoreClientFindPetsByTagsResponse contains the response from method SwaggerPetstoreClient.FindPetsByTags.
type SwaggerPetstoreClientFindPetsByTagsResponse struct {
	// Array of Pet
	PetArray []*Pet
}

// SwaggerPetstoreClientGetInventoryResponse contains the response from method SwaggerPetstoreClient.GetInventory.
type SwaggerPetstoreClientGetInventoryResponse struct {
	// Dictionary of <integer>
	Value map[string]*int32
}

// SwaggerPetstoreClientGetOrderByIDResponse contains the response from method SwaggerPetstoreClient.GetOrderByID.
type SwaggerPetstoreClientGetOrderByIDResponse struct {
	Order
}

// SwaggerPetstoreClientGetPetByIDResponse contains the response from method SwaggerPetstoreClient.GetPetByID.
type SwaggerPetstoreClientGetPetByIDResponse struct {
	Pet
}

// SwaggerPetstoreClientGetUserByNameResponse contains the response from method SwaggerPetstoreClient.GetUserByName.
type SwaggerPetstoreClientGetUserByNameResponse struct {
	User
}

// SwaggerPetstoreClientLoginUserResponse contains the response from method SwaggerPetstoreClient.LoginUser.
type SwaggerPetstoreClientLoginUserResponse struct {
	Value *string

	// XExpiresAfter contains the information returned from the X-Expires-After header response.
	XExpiresAfter *time.Time

	// XRateLimit contains the information returned from the X-Rate-Limit header response.
	XRateLimit *int32
}

// SwaggerPetstoreClientLogoutUserResponse contains the response from method SwaggerPetstoreClient.LogoutUser.
type SwaggerPetstoreClientLogoutUserResponse struct {
	// placeholder for future response values
}

// SwaggerPetstoreClientPlaceOrderResponse contains the response from method SwaggerPetstoreClient.PlaceOrder.
type SwaggerPetstoreClientPlaceOrderResponse struct {
	Order
}

// SwaggerPetstoreClientUpdatePetResponse contains the response from method SwaggerPetstoreClient.UpdatePet.
type SwaggerPetstoreClientUpdatePetResponse struct {
	// placeholder for future response values
}

// SwaggerPetstoreClientUpdatePetWithFormResponse contains the response from method SwaggerPetstoreClient.UpdatePetWithForm.
type SwaggerPetstoreClientUpdatePetWithFormResponse struct {
	// placeholder for future response values
}

// SwaggerPetstoreClientUpdateUserResponse contains the response from method SwaggerPetstoreClient.UpdateUser.
type SwaggerPetstoreClientUpdateUserResponse struct {
	// placeholder for future response values
}

// SwaggerPetstoreClientUploadFileResponse contains the response from method SwaggerPetstoreClient.UploadFile.
type SwaggerPetstoreClientUploadFileResponse struct {
	APIResponse
}

