# pylint: disable=too-many-lines
# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.9.2, generator: @autorest/python@6.1.9)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
import sys
from typing import Any, Callable, Dict, IO, List, Optional, TypeVar, Union, cast, overload
from xml.etree import ElementTree as ET

from azure.core.exceptions import (
    ClientAuthenticationError,
    HttpResponseError,
    ResourceExistsError,
    ResourceNotFoundError,
    ResourceNotModifiedError,
    map_error,
)
from azure.core.pipeline import PipelineResponse
from azure.core.pipeline.transport import AsyncHttpResponse
from azure.core.rest import HttpRequest
from azure.core.tracing.decorator_async import distributed_trace_async
from azure.core.utils import case_insensitive_dict

from ..._operations._operations import (
    build_add_pet_request,
    build_create_user_request,
    build_create_users_with_array_input_request,
    build_create_users_with_list_input_request,
    build_delete_order_request,
    build_delete_pet_request,
    build_delete_user_request,
    build_find_pets_by_status_request,
    build_find_pets_by_tags_request,
    build_get_inventory_request,
    build_get_order_by_id_request,
    build_get_pet_by_id_request,
    build_get_user_by_name_request,
    build_login_user_request,
    build_logout_user_request,
    build_place_order_request,
    build_update_pet_request,
    build_update_user_request,
)
from .._vendor import MixinABC, raise_if_not_implemented

if sys.version_info >= (3, 9):
    from collections.abc import MutableMapping
else:
    from typing import MutableMapping  # type: ignore  # pylint: disable=ungrouped-imports
JSON = MutableMapping[str, Any]  # pylint: disable=unsubscriptable-object
T = TypeVar("T")
ClsType = Optional[Callable[[PipelineResponse[HttpRequest, AsyncHttpResponse], T, Dict[str, Any]], Any]]


class SwaggerPetstoreOperationsMixin(MixinABC):
    def __init__(self) -> None:
        raise_if_not_implemented(
            self.__class__,
            [
                "upload_file",
                "update_pet_with_form",
            ],
        )

    @distributed_trace_async
    async def add_pet(self, body: ET.Element, **kwargs: Any) -> None:  # pylint: disable=inconsistent-return-statements
        """Add a new pet to the store.

        Add a new pet to the store.

        :param body: Pet object that needs to be added to the store. Required.
        :type body: ET.Element
        :return: None
        :rtype: None
        :raises ~azure.core.exceptions.HttpResponseError:

        Example:
            .. code-block:: python

                # JSON input template you can fill out and use as your body input.
                body = {
                    "name": "str",  # Required.
                    "photoUrls": [
                        "str"  # Required.
                    ],
                    "category": {
                        "id": 0,  # Optional.
                        "name": "str"  # Optional.
                    },
                    "id": 0,  # Optional.
                    "status": "str",  # Optional. pet status in the store. Known values are:
                      "available", "pending", and "sold".
                    "tags": [
                        {
                            "id": 0,  # Optional.
                            "name": "str"  # Optional.
                        }
                    ]
                }
        """
        error_map = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
        _params = kwargs.pop("params", {}) or {}

        content_type = kwargs.pop("content_type", _headers.pop("Content-Type", "application/json"))  # type: str
        cls = kwargs.pop("cls", None)  # type: ClsType[None]

        _content = body

        request = build_add_pet_request(
            content_type=content_type,
            content=_content,
            headers=_headers,
            params=_params,
        )
        request.url = self._client.format_url(request.url)  # type: ignore

        pipeline_response = await self._client._pipeline.run(  # type: ignore # pylint: disable=protected-access
            request, stream=False, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [405]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        if cls:
            return cls(pipeline_response, None, {})

    @distributed_trace_async
    async def update_pet(  # pylint: disable=inconsistent-return-statements
        self, body: ET.Element, **kwargs: Any
    ) -> None:
        """Update an existing pet.

        Update an existing pet.

        :param body: Pet object that needs to be added to the store. Required.
        :type body: ET.Element
        :return: None
        :rtype: None
        :raises ~azure.core.exceptions.HttpResponseError:

        Example:
            .. code-block:: python

                # JSON input template you can fill out and use as your body input.
                body = {
                    "name": "str",  # Required.
                    "photoUrls": [
                        "str"  # Required.
                    ],
                    "category": {
                        "id": 0,  # Optional.
                        "name": "str"  # Optional.
                    },
                    "id": 0,  # Optional.
                    "status": "str",  # Optional. pet status in the store. Known values are:
                      "available", "pending", and "sold".
                    "tags": [
                        {
                            "id": 0,  # Optional.
                            "name": "str"  # Optional.
                        }
                    ]
                }
        """
        error_map = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
        _params = kwargs.pop("params", {}) or {}

        content_type = kwargs.pop("content_type", _headers.pop("Content-Type", "application/json"))  # type: str
        cls = kwargs.pop("cls", None)  # type: ClsType[None]

        _content = body

        request = build_update_pet_request(
            content_type=content_type,
            content=_content,
            headers=_headers,
            params=_params,
        )
        request.url = self._client.format_url(request.url)  # type: ignore

        pipeline_response = await self._client._pipeline.run(  # type: ignore # pylint: disable=protected-access
            request, stream=False, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [400, 404, 405]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        if cls:
            return cls(pipeline_response, None, {})

    @distributed_trace_async
    async def find_pets_by_status(self, *, status: List[str], **kwargs: Any) -> Optional[ET.Element]:
        """Finds Pets by status.

        Multiple status values can be provided with comma separated strings.

        :keyword status: Status values that need to be considered for filter. Required.
        :paramtype status: list[str]
        :return: XML Element or None
        :rtype: ET.Element or None
        :raises ~azure.core.exceptions.HttpResponseError:

        Example:
            .. code-block:: python

                # response body for status code(s): 200, 200
                response == [
                    {
                        "name": "str",  # Required.
                        "photoUrls": [
                            "str"  # Required.
                        ],
                        "category": {
                            "id": 0,  # Optional.
                            "name": "str"  # Optional.
                        },
                        "id": 0,  # Optional.
                        "status": "str",  # Optional. pet status in the store. Known values
                          are: "available", "pending", and "sold".
                        "tags": [
                            {
                                "id": 0,  # Optional.
                                "name": "str"  # Optional.
                            }
                        ]
                    }
                ]
        """
        error_map = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = kwargs.pop("headers", {}) or {}
        _params = kwargs.pop("params", {}) or {}

        cls = kwargs.pop("cls", None)  # type: ClsType[Optional[ET.Element]]

        request = build_find_pets_by_status_request(
            status=status,
            headers=_headers,
            params=_params,
        )
        request.url = self._client.format_url(request.url)  # type: ignore

        pipeline_response = await self._client._pipeline.run(  # type: ignore # pylint: disable=protected-access
            request, stream=False, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [200, 200, 400]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        deserialized = None
        if response.status_code == 200:
            if response.content:
                deserialized = response.json()
            else:
                deserialized = None

        if response.status_code == 200:
            if response.content:
                deserialized = response.json()
            else:
                deserialized = None

        if cls:
            return cls(pipeline_response, deserialized, {})

        return deserialized

    @distributed_trace_async
    async def find_pets_by_tags(self, *, tags: List[str], **kwargs: Any) -> Optional[ET.Element]:
        """Finds Pets by tags.

        Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.

        :keyword tags: Tags to filter by. Required.
        :paramtype tags: list[str]
        :return: XML Element or None
        :rtype: ET.Element or None
        :raises ~azure.core.exceptions.HttpResponseError:

        Example:
            .. code-block:: python

                # response body for status code(s): 200, 200
                response == [
                    {
                        "name": "str",  # Required.
                        "photoUrls": [
                            "str"  # Required.
                        ],
                        "category": {
                            "id": 0,  # Optional.
                            "name": "str"  # Optional.
                        },
                        "id": 0,  # Optional.
                        "status": "str",  # Optional. pet status in the store. Known values
                          are: "available", "pending", and "sold".
                        "tags": [
                            {
                                "id": 0,  # Optional.
                                "name": "str"  # Optional.
                            }
                        ]
                    }
                ]
        """
        error_map = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = kwargs.pop("headers", {}) or {}
        _params = kwargs.pop("params", {}) or {}

        cls = kwargs.pop("cls", None)  # type: ClsType[Optional[ET.Element]]

        request = build_find_pets_by_tags_request(
            tags=tags,
            headers=_headers,
            params=_params,
        )
        request.url = self._client.format_url(request.url)  # type: ignore

        pipeline_response = await self._client._pipeline.run(  # type: ignore # pylint: disable=protected-access
            request, stream=False, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [200, 200, 400]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        deserialized = None
        if response.status_code == 200:
            if response.content:
                deserialized = response.json()
            else:
                deserialized = None

        if response.status_code == 200:
            if response.content:
                deserialized = response.json()
            else:
                deserialized = None

        if cls:
            return cls(pipeline_response, deserialized, {})

        return deserialized

    @distributed_trace_async
    async def get_pet_by_id(self, pet_id: int, **kwargs: Any) -> Optional[ET.Element]:
        """Find pet by ID.

        Returns a single pet.

        :param pet_id: ID of pet to return. Required.
        :type pet_id: int
        :return: XML Element or None
        :rtype: ET.Element or None
        :raises ~azure.core.exceptions.HttpResponseError:

        Example:
            .. code-block:: python

                # response body for status code(s): 200, 200
                response == {
                    "name": "str",  # Required.
                    "photoUrls": [
                        "str"  # Required.
                    ],
                    "category": {
                        "id": 0,  # Optional.
                        "name": "str"  # Optional.
                    },
                    "id": 0,  # Optional.
                    "status": "str",  # Optional. pet status in the store. Known values are:
                      "available", "pending", and "sold".
                    "tags": [
                        {
                            "id": 0,  # Optional.
                            "name": "str"  # Optional.
                        }
                    ]
                }
        """
        error_map = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = kwargs.pop("headers", {}) or {}
        _params = kwargs.pop("params", {}) or {}

        cls = kwargs.pop("cls", None)  # type: ClsType[Optional[ET.Element]]

        request = build_get_pet_by_id_request(
            pet_id=pet_id,
            headers=_headers,
            params=_params,
        )
        request.url = self._client.format_url(request.url)  # type: ignore

        pipeline_response = await self._client._pipeline.run(  # type: ignore # pylint: disable=protected-access
            request, stream=False, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [200, 200, 400, 404]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        deserialized = None
        if response.status_code == 200:
            if response.content:
                deserialized = ET.fromstring(response.text())
            else:
                deserialized = None

        if response.status_code == 200:
            if response.content:
                deserialized = ET.fromstring(response.text())
            else:
                deserialized = None

        if cls:
            return cls(pipeline_response, deserialized, {})

        return deserialized

    @distributed_trace_async
    async def delete_pet(  # pylint: disable=inconsistent-return-statements
        self, pet_id: int, *, api_key: Optional[str] = None, **kwargs: Any
    ) -> None:
        """Deletes a pet.

        Deletes a pet.

        :param pet_id: Pet id to delete. Required.
        :type pet_id: int
        :keyword api_key: Default value is None.
        :paramtype api_key: str
        :return: None
        :rtype: None
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = kwargs.pop("headers", {}) or {}
        _params = kwargs.pop("params", {}) or {}

        cls = kwargs.pop("cls", None)  # type: ClsType[None]

        request = build_delete_pet_request(
            pet_id=pet_id,
            api_key=api_key,
            headers=_headers,
            params=_params,
        )
        request.url = self._client.format_url(request.url)  # type: ignore

        pipeline_response = await self._client._pipeline.run(  # type: ignore # pylint: disable=protected-access
            request, stream=False, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [400, 404]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        if cls:
            return cls(pipeline_response, None, {})

    @distributed_trace_async
    async def place_order(self, body: ET.Element, **kwargs: Any) -> Optional[ET.Element]:
        """Place an order for a pet.

        Place an order for a pet.

        :param body: order placed for purchasing the pet. Required.
        :type body: ET.Element
        :return: XML Element or None
        :rtype: ET.Element or None
        :raises ~azure.core.exceptions.HttpResponseError:

        Example:
            .. code-block:: python

                # JSON input template you can fill out and use as your body input.
                body = {
                    "complete": bool,  # Optional.
                    "id": 0,  # Optional.
                    "petId": 0,  # Optional.
                    "quantity": 0,  # Optional.
                    "shipDate": "2020-02-20 00:00:00",  # Optional.
                    "status": "str"  # Optional. Order Status. Known values are: "placed",
                      "approved", and "delivered".
                }

                # response body for status code(s): 200, 200
                response == {
                    "complete": bool,  # Optional.
                    "id": 0,  # Optional.
                    "petId": 0,  # Optional.
                    "quantity": 0,  # Optional.
                    "shipDate": "2020-02-20 00:00:00",  # Optional.
                    "status": "str"  # Optional. Order Status. Known values are: "placed",
                      "approved", and "delivered".
                }
        """
        error_map = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
        _params = kwargs.pop("params", {}) or {}

        content_type = kwargs.pop("content_type", _headers.pop("Content-Type", "application/json"))  # type: str
        cls = kwargs.pop("cls", None)  # type: ClsType[Optional[ET.Element]]

        _json = body

        request = build_place_order_request(
            content_type=content_type,
            json=_json,
            headers=_headers,
            params=_params,
        )
        request.url = self._client.format_url(request.url)  # type: ignore

        pipeline_response = await self._client._pipeline.run(  # type: ignore # pylint: disable=protected-access
            request, stream=False, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [200, 200, 400]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        deserialized = None
        if response.status_code == 200:
            if response.content:
                deserialized = ET.fromstring(response.text())
            else:
                deserialized = None

        if response.status_code == 200:
            if response.content:
                deserialized = ET.fromstring(response.text())
            else:
                deserialized = None

        if cls:
            return cls(pipeline_response, deserialized, {})

        return deserialized

    @distributed_trace_async
    async def get_order_by_id(self, order_id: int, **kwargs: Any) -> Optional[ET.Element]:
        """Find purchase order by ID.

        For valid response try integer IDs with value >= 1 and <= 10. Other values will generated
        exceptions.

        :param order_id: ID of pet that needs to be fetched. Required.
        :type order_id: int
        :return: XML Element or None
        :rtype: ET.Element or None
        :raises ~azure.core.exceptions.HttpResponseError:

        Example:
            .. code-block:: python

                # response body for status code(s): 200, 200
                response == {
                    "complete": bool,  # Optional.
                    "id": 0,  # Optional.
                    "petId": 0,  # Optional.
                    "quantity": 0,  # Optional.
                    "shipDate": "2020-02-20 00:00:00",  # Optional.
                    "status": "str"  # Optional. Order Status. Known values are: "placed",
                      "approved", and "delivered".
                }
        """
        error_map = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = kwargs.pop("headers", {}) or {}
        _params = kwargs.pop("params", {}) or {}

        cls = kwargs.pop("cls", None)  # type: ClsType[Optional[ET.Element]]

        request = build_get_order_by_id_request(
            order_id=order_id,
            headers=_headers,
            params=_params,
        )
        request.url = self._client.format_url(request.url)  # type: ignore

        pipeline_response = await self._client._pipeline.run(  # type: ignore # pylint: disable=protected-access
            request, stream=False, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [200, 200, 400, 404]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        deserialized = None
        if response.status_code == 200:
            if response.content:
                deserialized = ET.fromstring(response.text())
            else:
                deserialized = None

        if response.status_code == 200:
            if response.content:
                deserialized = ET.fromstring(response.text())
            else:
                deserialized = None

        if cls:
            return cls(pipeline_response, deserialized, {})

        return deserialized

    @distributed_trace_async
    async def delete_order(  # pylint: disable=inconsistent-return-statements
        self, order_id: int, **kwargs: Any
    ) -> None:
        """Delete purchase order by ID.

        For valid response try integer IDs with positive integer value. Negative or non-integer values
        will generate API errors.

        :param order_id: ID of the order that needs to be deleted. Required.
        :type order_id: int
        :return: None
        :rtype: None
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = kwargs.pop("headers", {}) or {}
        _params = kwargs.pop("params", {}) or {}

        cls = kwargs.pop("cls", None)  # type: ClsType[None]

        request = build_delete_order_request(
            order_id=order_id,
            headers=_headers,
            params=_params,
        )
        request.url = self._client.format_url(request.url)  # type: ignore

        pipeline_response = await self._client._pipeline.run(  # type: ignore # pylint: disable=protected-access
            request, stream=False, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [400, 404]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        if cls:
            return cls(pipeline_response, None, {})

    @distributed_trace_async
    async def get_inventory(self, **kwargs: Any) -> Dict[str, int]:
        """Returns pet inventories by status.

        Returns a map of status codes to quantities.

        :return: dict mapping str to int
        :rtype: dict[str, int]
        :raises ~azure.core.exceptions.HttpResponseError:

        Example:
            .. code-block:: python

                # response body for status code(s): 200
                response == {
                    "str": 0  # Optional.
                }
        """
        error_map = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = kwargs.pop("headers", {}) or {}
        _params = kwargs.pop("params", {}) or {}

        cls = kwargs.pop("cls", None)  # type: ClsType[Dict[str, int]]

        request = build_get_inventory_request(
            headers=_headers,
            params=_params,
        )
        request.url = self._client.format_url(request.url)  # type: ignore

        pipeline_response = await self._client._pipeline.run(  # type: ignore # pylint: disable=protected-access
            request, stream=False, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [200]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        if response.content:
            deserialized = response.json()
        else:
            deserialized = None

        if cls:
            return cls(pipeline_response, cast(Dict[str, int], deserialized), {})

        return cast(Dict[str, int], deserialized)

    @overload
    async def create_users_with_array_input(  # pylint: disable=inconsistent-return-statements
        self, body: ET.Element, *, content_type: str = "application/json", **kwargs: Any
    ) -> None:
        """Creates list of users with given input array.

        Creates list of users with given input array.

        :param body: List of user object. Required.
        :type body: ET.Element
        :keyword content_type: Body Parameter content-type. Content type parameter for JSON body.
         Default value is "application/json".
        :paramtype content_type: str
        :return: None
        :rtype: None
        :raises ~azure.core.exceptions.HttpResponseError:

        Example:
            .. code-block:: python

                # JSON input template you can fill out and use as your body input.
                body = [
                    {
                        "email": "str",  # Optional.
                        "firstName": "str",  # Optional.
                        "id": 0,  # Optional.
                        "lastName": "str",  # Optional.
                        "password": "str",  # Optional.
                        "phone": "str",  # Optional.
                        "userStatus": 0,  # Optional. User Status.
                        "username": "str"  # Optional.
                    }
                ]
        """

    @overload
    async def create_users_with_array_input(  # pylint: disable=inconsistent-return-statements
        self, body: IO, *, content_type: str = "application/json", **kwargs: Any
    ) -> None:
        """Creates list of users with given input array.

        Creates list of users with given input array.

        :param body: List of user object. Required.
        :type body: IO
        :keyword content_type: Body Parameter content-type. Content type parameter for binary body.
         Default value is "application/json".
        :paramtype content_type: str
        :return: None
        :rtype: None
        :raises ~azure.core.exceptions.HttpResponseError:
        """

    @distributed_trace_async
    async def create_users_with_array_input(  # pylint: disable=inconsistent-return-statements
        self, body: Union[ET.Element, IO], **kwargs: Any
    ) -> None:
        """Creates list of users with given input array.

        Creates list of users with given input array.

        :param body: List of user object. Is either a list type or a IO type. Required.
        :type body: ET.Element or IO
        :keyword content_type: Body Parameter content-type. Known values are: 'application/json'.
         Default value is None.
        :paramtype content_type: str
        :return: None
        :rtype: None
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
        _params = kwargs.pop("params", {}) or {}

        content_type = kwargs.pop("content_type", _headers.pop("Content-Type", None))  # type: Optional[str]
        cls = kwargs.pop("cls", None)  # type: ClsType[None]

        content_type = content_type or "application/json"
        _json = None
        _content = None
        if isinstance(body, (IO, bytes)):
            _content = body
        else:
            _json = body

        request = build_create_users_with_array_input_request(
            content_type=content_type,
            json=_json,
            content=_content,
            headers=_headers,
            params=_params,
        )
        request.url = self._client.format_url(request.url)  # type: ignore

        pipeline_response = await self._client._pipeline.run(  # type: ignore # pylint: disable=protected-access
            request, stream=False, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in []:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        if cls:
            return cls(pipeline_response, None, {})

    @overload
    async def create_users_with_list_input(  # pylint: disable=inconsistent-return-statements
        self, body: ET.Element, *, content_type: str = "application/json", **kwargs: Any
    ) -> None:
        """Creates list of users with given input array.

        Creates list of users with given input array.

        :param body: List of user object. Required.
        :type body: ET.Element
        :keyword content_type: Body Parameter content-type. Content type parameter for JSON body.
         Default value is "application/json".
        :paramtype content_type: str
        :return: None
        :rtype: None
        :raises ~azure.core.exceptions.HttpResponseError:

        Example:
            .. code-block:: python

                # JSON input template you can fill out and use as your body input.
                body = [
                    {
                        "email": "str",  # Optional.
                        "firstName": "str",  # Optional.
                        "id": 0,  # Optional.
                        "lastName": "str",  # Optional.
                        "password": "str",  # Optional.
                        "phone": "str",  # Optional.
                        "userStatus": 0,  # Optional. User Status.
                        "username": "str"  # Optional.
                    }
                ]
        """

    @overload
    async def create_users_with_list_input(  # pylint: disable=inconsistent-return-statements
        self, body: IO, *, content_type: str = "application/json", **kwargs: Any
    ) -> None:
        """Creates list of users with given input array.

        Creates list of users with given input array.

        :param body: List of user object. Required.
        :type body: IO
        :keyword content_type: Body Parameter content-type. Content type parameter for binary body.
         Default value is "application/json".
        :paramtype content_type: str
        :return: None
        :rtype: None
        :raises ~azure.core.exceptions.HttpResponseError:
        """

    @distributed_trace_async
    async def create_users_with_list_input(  # pylint: disable=inconsistent-return-statements
        self, body: Union[ET.Element, IO], **kwargs: Any
    ) -> None:
        """Creates list of users with given input array.

        Creates list of users with given input array.

        :param body: List of user object. Is either a list type or a IO type. Required.
        :type body: ET.Element or IO
        :keyword content_type: Body Parameter content-type. Known values are: 'application/json'.
         Default value is None.
        :paramtype content_type: str
        :return: None
        :rtype: None
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
        _params = kwargs.pop("params", {}) or {}

        content_type = kwargs.pop("content_type", _headers.pop("Content-Type", None))  # type: Optional[str]
        cls = kwargs.pop("cls", None)  # type: ClsType[None]

        content_type = content_type or "application/json"
        _json = None
        _content = None
        if isinstance(body, (IO, bytes)):
            _content = body
        else:
            _json = body

        request = build_create_users_with_list_input_request(
            content_type=content_type,
            json=_json,
            content=_content,
            headers=_headers,
            params=_params,
        )
        request.url = self._client.format_url(request.url)  # type: ignore

        pipeline_response = await self._client._pipeline.run(  # type: ignore # pylint: disable=protected-access
            request, stream=False, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in []:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        if cls:
            return cls(pipeline_response, None, {})

    @distributed_trace_async
    async def get_user_by_name(self, username: str, **kwargs: Any) -> Optional[ET.Element]:
        """Get user by user name.

        Get user by user name.

        :param username: The name that needs to be fetched. Use user1 for testing. Required.
        :type username: str
        :return: XML Element or None
        :rtype: ET.Element or None
        :raises ~azure.core.exceptions.HttpResponseError:

        Example:
            .. code-block:: python

                # response body for status code(s): 200, 200
                response == {
                    "email": "str",  # Optional.
                    "firstName": "str",  # Optional.
                    "id": 0,  # Optional.
                    "lastName": "str",  # Optional.
                    "password": "str",  # Optional.
                    "phone": "str",  # Optional.
                    "userStatus": 0,  # Optional. User Status.
                    "username": "str"  # Optional.
                }
        """
        error_map = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = kwargs.pop("headers", {}) or {}
        _params = kwargs.pop("params", {}) or {}

        cls = kwargs.pop("cls", None)  # type: ClsType[Optional[ET.Element]]

        request = build_get_user_by_name_request(
            username=username,
            headers=_headers,
            params=_params,
        )
        request.url = self._client.format_url(request.url)  # type: ignore

        pipeline_response = await self._client._pipeline.run(  # type: ignore # pylint: disable=protected-access
            request, stream=False, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [200, 200, 400, 404]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        deserialized = None
        if response.status_code == 200:
            if response.content:
                deserialized = ET.fromstring(response.text())
            else:
                deserialized = None

        if response.status_code == 200:
            if response.content:
                deserialized = ET.fromstring(response.text())
            else:
                deserialized = None

        if cls:
            return cls(pipeline_response, deserialized, {})

        return deserialized

    @distributed_trace_async
    async def update_user(  # pylint: disable=inconsistent-return-statements
        self, username: str, body: ET.Element, **kwargs: Any
    ) -> None:
        """Updated user.

        This can only be done by the logged in user.

        :param username: name that need to be updated. Required.
        :type username: str
        :param body: Updated user object. Required.
        :type body: ET.Element
        :return: None
        :rtype: None
        :raises ~azure.core.exceptions.HttpResponseError:

        Example:
            .. code-block:: python

                # JSON input template you can fill out and use as your body input.
                body = {
                    "email": "str",  # Optional.
                    "firstName": "str",  # Optional.
                    "id": 0,  # Optional.
                    "lastName": "str",  # Optional.
                    "password": "str",  # Optional.
                    "phone": "str",  # Optional.
                    "userStatus": 0,  # Optional. User Status.
                    "username": "str"  # Optional.
                }
        """
        error_map = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
        _params = kwargs.pop("params", {}) or {}

        content_type = kwargs.pop("content_type", _headers.pop("Content-Type", "application/json"))  # type: str
        cls = kwargs.pop("cls", None)  # type: ClsType[None]

        _json = body

        request = build_update_user_request(
            username=username,
            content_type=content_type,
            json=_json,
            headers=_headers,
            params=_params,
        )
        request.url = self._client.format_url(request.url)  # type: ignore

        pipeline_response = await self._client._pipeline.run(  # type: ignore # pylint: disable=protected-access
            request, stream=False, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [400, 404]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        if cls:
            return cls(pipeline_response, None, {})

    @distributed_trace_async
    async def delete_user(self, username: str, **kwargs: Any) -> None:  # pylint: disable=inconsistent-return-statements
        """Delete user.

        This can only be done by the logged in user.

        :param username: The name that needs to be deleted. Required.
        :type username: str
        :return: None
        :rtype: None
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = kwargs.pop("headers", {}) or {}
        _params = kwargs.pop("params", {}) or {}

        cls = kwargs.pop("cls", None)  # type: ClsType[None]

        request = build_delete_user_request(
            username=username,
            headers=_headers,
            params=_params,
        )
        request.url = self._client.format_url(request.url)  # type: ignore

        pipeline_response = await self._client._pipeline.run(  # type: ignore # pylint: disable=protected-access
            request, stream=False, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [400, 404]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        if cls:
            return cls(pipeline_response, None, {})

    @distributed_trace_async
    async def login_user(self, *, username: str, password: str, **kwargs: Any) -> Optional[str]:
        """Logs user into the system.

        Logs user into the system.

        :keyword username: The user name for login. Required.
        :paramtype username: str
        :keyword password: The password for login in clear text. Required.
        :paramtype password: str
        :return: str or None
        :rtype: str or None
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = kwargs.pop("headers", {}) or {}
        _params = kwargs.pop("params", {}) or {}

        cls = kwargs.pop("cls", None)  # type: ClsType[Optional[str]]

        request = build_login_user_request(
            username=username,
            password=password,
            headers=_headers,
            params=_params,
        )
        request.url = self._client.format_url(request.url)  # type: ignore

        pipeline_response = await self._client._pipeline.run(  # type: ignore # pylint: disable=protected-access
            request, stream=False, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [200, 200, 400]:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        deserialized = None
        response_headers = {}
        if response.status_code == 200:
            response_headers["X-Expires-After"] = self._deserialize("iso-8601", response.headers.get("X-Expires-After"))
            response_headers["X-Rate-Limit"] = self._deserialize("int", response.headers.get("X-Rate-Limit"))

            if response.content:
                deserialized = response.json()
            else:
                deserialized = None

        if response.status_code == 200:
            response_headers["X-Expires-After"] = self._deserialize("iso-8601", response.headers.get("X-Expires-After"))
            response_headers["X-Rate-Limit"] = self._deserialize("int", response.headers.get("X-Rate-Limit"))

            if response.content:
                deserialized = response.json()
            else:
                deserialized = None

        if cls:
            return cls(pipeline_response, deserialized, response_headers)

        return deserialized

    @distributed_trace_async
    async def logout_user(self, **kwargs: Any) -> None:  # pylint: disable=inconsistent-return-statements
        """Logs out current logged in user session.

        Logs out current logged in user session.

        :return: None
        :rtype: None
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = kwargs.pop("headers", {}) or {}
        _params = kwargs.pop("params", {}) or {}

        cls = kwargs.pop("cls", None)  # type: ClsType[None]

        request = build_logout_user_request(
            headers=_headers,
            params=_params,
        )
        request.url = self._client.format_url(request.url)  # type: ignore

        pipeline_response = await self._client._pipeline.run(  # type: ignore # pylint: disable=protected-access
            request, stream=False, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in []:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        if cls:
            return cls(pipeline_response, None, {})

    @distributed_trace_async
    async def create_user(  # pylint: disable=inconsistent-return-statements
        self, body: ET.Element, **kwargs: Any
    ) -> None:
        """Create user.

        This can only be done by the logged in user.

        :param body: Created user object. Required.
        :type body: ET.Element
        :return: None
        :rtype: None
        :raises ~azure.core.exceptions.HttpResponseError:

        Example:
            .. code-block:: python

                # JSON input template you can fill out and use as your body input.
                body = {
                    "email": "str",  # Optional.
                    "firstName": "str",  # Optional.
                    "id": 0,  # Optional.
                    "lastName": "str",  # Optional.
                    "password": "str",  # Optional.
                    "phone": "str",  # Optional.
                    "userStatus": 0,  # Optional. User Status.
                    "username": "str"  # Optional.
                }
        """
        error_map = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
        _params = kwargs.pop("params", {}) or {}

        content_type = kwargs.pop("content_type", _headers.pop("Content-Type", "application/json"))  # type: str
        cls = kwargs.pop("cls", None)  # type: ClsType[None]

        _json = body

        request = build_create_user_request(
            content_type=content_type,
            json=_json,
            headers=_headers,
            params=_params,
        )
        request.url = self._client.format_url(request.url)  # type: ignore

        pipeline_response = await self._client._pipeline.run(  # type: ignore # pylint: disable=protected-access
            request, stream=False, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in []:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)

        if cls:
            return cls(pipeline_response, None, {})
